### ISSUE TITLE
add explanations

### ISSUE THREAD

**Issue by rocambille** [rocambille/library-of-twitter#9]
add some kind of header/footer in the page to explain the context and the purpose of this page:

* the inspiration of th Library of Babel
* the link to the github
* maybe some references to hacktoberfest
* any relevant thing

**Comment by sandeep3136** [comment]
assign to me

**Comment by rocambille** [comment]
Here are some insights. First, the plot from "The Library of Babel" taken from [wikipedia](https://en.m.wikipedia.org/wiki/The_Library_of_Babel#Plot):

> [The] narrator describes how his universe consists of an enormous expanse of adjacent hexagonal rooms. In each room, [...] walls of bookshelves. Though the order and content of the books are random and apparently completely meaningless, the inhabitants believe that the books contain every possible ordering of just 25 basic characters (22 letters, the period, the comma, and space). Though the vast majority of the books in this universe are pure gibberish, the library also must contain [...] all useful information, including predictions of the future, biographies of any person, and translations of every book in all languages.

So the Library of Twitter is designed after this short story. It proposes a random tweet generator, with the hope that someday a useful tweet will be generated... and shared with Humanity
